# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgNuA5M2po5AfrP6SDC_iCg2mpwySDQ0
"""

# app/app.py

import streamlit as st
import pandas as pd
import joblib
from utils import load_model_and_scaler, make_prediction

# Load model
model = load_model_and_scaler()

# Streamlit UI
st.set_page_config(page_title="Energy Consumption Forecast", layout="centered")

st.title("⚡ Smart Grid Energy Consumption Forecasting")

st.markdown("""
Welcome! This app predicts the energy consumption based on time and previous consumption data.
Enter the inputs below and get an instant prediction.
""")

# Input form
with st.form("prediction_form"):
    hour = st.slider('Hour of Day (0-23)', 0, 23, 12)
    day_of_week = st.slider('Day of Week (0=Monday, 6=Sunday)', 0, 6, 3)
    month = st.slider('Month (1-12)', 1, 12, 6)
    lag_1 = st.number_input('Previous Hour Consumption (kWh)', value=500.0)
    rolling_mean_24h = st.number_input('24H Rolling Mean Consumption (kWh)', value=480.0)

    submitted = st.form_submit_button("Predict Consumption")

if submitted:
    input_data = {
        'hour': hour,
        'day_of_week': day_of_week,
        'month': month,
        'lag_1': lag_1,
        'rolling_mean_24h': rolling_mean_24h
    }

    prediction = make_prediction(model, input_data)
    st.success(f"Predicted Energy Consumption: **{prediction:.2f} kWh**")