# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lr8Oqk3XVQ7RAOQs65QAUDxHOUAJuXd-
"""

# app/utils.py

import joblib
import pandas as pd

def load_model_and_scaler():
    """Load the trained model from disk."""
    model = joblib.load('../models/final_model.pkl')
    return model

def make_prediction(model, input_data):
    """Predict using the model and input data."""
    input_df = pd.DataFrame([input_data])
    prediction = model.predict(input_df)[0]
    return prediction